inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'build/**/*'

Metrics/LineLength:
  Max: 110
  Exclude:
    - 'Rakefile'

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/vagrant-service-manager.rb'
