inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'build/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Rakefile'

Metrics/ClassLength:
  Max: 209
  Exclude:
    - 'lib/vagrant-service-manager/command.rb'
